#!/bin/sh

openssl_includedir=`pkg-config --variable=includedir openssl`
openssl_libdir=`pkg-config --variable=libdir openssl`
if test -n "$openssl_includedir"
then
    openssl_cflags="-I$openssl_includedir"
fi
if test -n "$openssl_libdir"
then
    openssl_ldflags="-I$openssl_libdir"
fi

if test "$1" = "init"
then
    export LDFLAGS="${openssl_ldflags} -L$HOME/lib"
    export CFLAGS="${openssl_cflags} -I$HOME/include"

    autoreconf --force
    aclocal
    autoheader
    autoreconf
    automake --add-missing
    libtoolize
    make distclean
    autoreconf
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev"
then
    export LDFLAGS="${openssl_ldflags} -L$HOME/lib"
    export CFLAGS="${openssl_cflags} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug

elif test "$1" = "dev-static"
then
    export LDFLAGS="${openssl_ldflags} -L$HOME/lib"
    export CFLAGS="${openssl_cflags} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-debug --enable-allstatic

elif test "$1" = "dev-ndebug"
then
    export LDFLAGS="${openssl_ldflags} -L$HOME/lib"
    export CFLAGS="${openssl_cflags} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME

elif test "$1" = "dev-ndebug-static"
then
    export LDFLAGS="${openssl_ldflags} -L$HOME/lib"
    export CFLAGS="${openssl_cflags} -I$HOME/include"
    autoreconf --force
    ./configure --prefix=$HOME --enable-allstatic --enable-lto

elif test "$1" = "dist"
then
    unset LDFLAGS
    unset CFLAGS
    autoreconf --force
    ./configure
    make dist

    if test -f port/distinfo
    then
        truncate -s0 port/distinfo
    fi
    for i in *.tar.gz
    do
        cp -v $i /data0/mkushnir/distfiles/
        if test -f port/distinfo
        then
            /sbin/sha256 $i >port/distinfo
            echo "SIZE ($i) = `stat -f%z $i`" >>port/distinfo
        fi
    done

elif test "$1" = "du"
then
    find . -type f -name '*.[ch]' -ls | awk '{print $7;}' | (n=0; while read a; do n=$((n + a)); done; echo $n)

else
    echo "`basename $0` {init|dev[-static]|dist|dev-ndebug[-static]}"
fi
